### Get all categories
GET http://localhost:3000/api/categories
Accept: application/json

### Create new category
POST http://localhost:3000/api/categories
Accept: application/json
Content-Type: application/json

{
  "name" : "Computer"
}

### Get category by Id
GET http://localhost:3000/api/categories/1
Accept: application/json

### Update category by Id
PUT http://localhost:3000/api/categories/1
Accept: application/json
Content-Type: application/json

{
  "name" : "Fashion"
}

### Delete category by Id
DELETE http://localhost:3000/api/categories/1
Accept: application/json
Content-Type: application/json